<script src="{{ asset('assets/js/app.js') }}"></script>
<script src="{{ asset('assets/icons/font-awesome/js/all.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jquery/jquery.sparkline.min.js') }}"></script>
<!-- Perfect-scrollbar js -->
<script src="{{ asset('assets/js/components/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('assets/js/components/pscroll.js') }}"></script>
<script src="{{ asset('assets/js/components/pscroll-1.js') }}"></script>
<!-- Sidemenu js -->
<script src="{{ asset('assets/js/components/sidemenu.js') }}"></script>
<script src="{{ asset('assets/js/components/sidebar.js') }}"></script>
<!-- Sticky js -->
<script src="{{ asset('assets/js/components/sticky.js') }}"></script>
<!-- Custom js -->
<script src="{{ asset('assets/js/components/custom.js') }}"></script>

<!-- 3rd Party -->
<script src="{{ asset('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/dataTables.bootstrap5.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/buttons.bootstrap5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/buttons.bootstrap5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatable/js/dataTables.rowGroup.min.js') }}"></script>
<script src="{{ asset('assets/plugins/select2/select2.full.min.js') }}"></script>
<script src="{{ asset('assets/plugins/toastr/toastr.min.js') }}"></script>
@yield('script')
